config/routes.rb
Rails.application.routes.draw do
  
  
  get 'home/index'

  # Back admin routes start
  authenticate :user do
  namespace :admin do
    resources :visits do
      member do
        get 'print'
        get 'preview'
        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :tickets do
      member do
        get 'print'
        get 'preview'
        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :users do

    end
    resources :companies do
      member do

        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :deals do

    end
    resources :expenses do

    end

    # Admin root
    root to: 'application#index'
  end
  end
  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # Application root
 # root to: 'application#home'
  # Front routes end
 

  root to: 'creatives#index'
end

app/models/company.rb
class Company < ApplicationRecord
	 
 
  before_create :calculate_margin
  before_update :calculate_margin
  before_create :calculate_debit
  before_update :calculate_debit
  before_create :set_client_status
  before_update :set_client_status
  before_update :client_debit_payment, if: :creditAmount?

  belongs_to :user


 def client_debit_payment
   if self.debitAmount.to_f > 0.0
   self.paidAmount = self.paidAmount.to_f + self.creditAmount.to_f
   self.debitAmount = self.debitAmount.to_f - self.creditAmount.to_f
  end
  if self.debitAmount.to_f == 0.0
    self.status = "Cleared"
    else
      self.status = "Not Cleared"
    end
  
    self.creditAmount = 0.0
end
 def calculate_margin
    self.profit = self.salePrice.to_f - self.actualCost.to_f
  end 

  def calculate_debit
    self.debitAmount = self.salePrice.to_f - self.paidAmount.to_f
  end
  def set_client_status
  	if self.salePrice.to_f - self.paidAmount.to_f == 0.0
  		self.status = "Cleared"
  	else
  		self.status = "Not Cleared"
    end
 end
end

app/controllers/admin/companies_controller.rb
  module Admin
  class CompaniesController < Admin::ApplicationController
    respond_to :json, :html
    before_action :set_company, only: [:show, :edit, :update, :destroy, :payment_edit]
    layout  'admin/layouts/admin'

    # GET /companies
    # GET /companies.json
    def index
     if  current_user.admin?
      @companies = Company.all
     else
      @companies = current_user.companies
    end
  end 
    def payment_edit

    end


     # Post
    def debit_payment
      if current_user.admin?
      @company = Company.find(params[:company][:id])
    else
      @company = current_user.companies.find(params[:company][:id])
    end 
      if @company.update(company_params)
        flash[:notice] = t('admin.companies.update.success')
        redirect_to admin_companies_url 
      else
        flash[:warning] = @company.errors.full_messages.uniq.join(', ')
        respond_with :edit, :admin, :company
      end
    end

    # GET /users/1
    # GET /users/1.json
    def debit
      @companies =[]
      if current_user.admin?
      companies = Company.where(status: "Not Cleared").ids
      else
       companies = current_user.companies.where(status: "Not Cleared").ids
      end 

      companies.each do | company |
        c = Company.find(company)
        @companies << c
      end
      @companies
    end

    # GET /companies/1
    # GET /companies/1.json
    def show
        respond_to do |format|
      format.html   
      end 
    end
  

    # GET /companies/new
    def new
      @company = Company.new
      @url = admin_companies_path
    end

    # GET /companies/1/edit
    def edit
      @url = admin_company_path(@company)
    end

    # POST /companies
    # POST /companies.json
    def create
      @company = current_user.companies.build(company_params)

      if @company.save
        flash[:notice] = t('admin.companies.create.success')
        redirect_to admin_companies_url 
      else
        flash[:warning] = @company.errors.full_messages.uniq.join(', ')
        respond_with :new, :admin, :company
      end
    end

    # PATCH/PUT /companies/1
    # PATCH/PUT /companies/1.json
    def update
      if @company.update(company_params)
        flash[:notice] = t('admin.companies.update.success')
        redirect_to admin_companies_url 
      else
        flash[:warning] = @company.errors.full_messages.uniq.join(', ')
        respond_with :edit, :admin, :company
      end
    end

    # DELETE /companies/1
    # DELETE /companies/1.json
    def destroy
      @company.destroy
      respond_to do |format|
        format.html { redirect_to admin_companies_path, notice: t('admin.companies.destroy.success') }
        format.json { head :no_content }
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    private def set_company

      
      if current_user.admin?
        if Company.exists?(params[:id])
        @company = Company.find(params[:id])
        else
        render :file => "#{Rails.root}/public/404",  layout: false, status: :not_found
        end 

      else
        
        if current_user.companies.exists?(params[:id])
        @company = current_user.companies.find(params[:id])
        else
        render :file => "#{Rails.root}/public/404",  layout: false, status: :not_found
        end 
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    private def company_params
      params.require(:company).permit(Company.attribute_names.map(&:to_sym))
    end
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper

def status_value (record) 
	
 if record == "Bye"

 status = "Debit"
else
 status = "Credit"
    
  end
end
end 

app/views/admin/companies/_debitPaymentform.html.erb
<div class="form-group">
  <%= f.label :Enter_Amount %>
  <%= f.number_field :creditAmount, class: "form-control", placeholder: "Enter Amount", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<%= f.hidden_field :paidAmount, :value => @company.paidAmount %>
<%= f.hidden_field :debitAmount, :value => @company.debitAmount %>
<%= f.hidden_field :status, :value => @company.status %>
<%= f.hidden_field :id, :value => @company.id %>

app/views/admin/companies/_form.html.erb
<div class="form-group">
  <%= f.label :Name , :class => "col-xs-12", style:"padding-left:0px;"%>
  <%= f.select :name, options_for_select(current_user.admin? ? Deal.pluck(:name) : current_user.deals.pluck(:name),selected: @company.name.present? ? @company.name : ''), {:include_blank => true}, {:multiple => false, :class => "js-example-basic-single col-xs-12", :label => false,:style => "margin-left:25px;", :data => {:placeholder => ' select visa type details'}}%>  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :visa_or_ticket , :class => "col-xs-12", style:"padding-left:0px;"%>
  <%= f.select :visa_or_ticket, options_for_select(['Visa', 'Ticket'],selected: @company.visa_or_ticket.present? ? @company.visa_or_ticket : ''), {:include_blank => true}, {:multiple => false, :class => "js-example-basic-single col-xs-12", :label => false,:style => "margin-left:25px;", :data => {:placeholder => ' select visa or ticket'}}%>  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Buy_Or_Sell , :class => "col-xs-12", style:"padding-left:0px;"%>
  <%= f.select :bye_or_sell, options_for_select(['Buy', 'Sell'],selected: @company.bye_or_sell.present? ? @company.bye_or_sell : ''), {:include_blank => true}, {:multiple => false, :class => "js-example-basic-single col-xs-12", :label => false,:style => "margin-left:25px;", :data => {:placeholder => ' Buy Or Sell'}}%>  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Quantity %>
  <%= f.number_field :quantity, class: "form-control", placeholder: "Enter Quantity", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Sale_Price %>
  <%= f.number_field :salePrice, class: "form-control", placeholder: "Enter Amount", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Paid_Amount %>
  <%= f.number_field :paidAmount, class: "form-control", placeholder: "Enter Amount", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Actual_Cost %>
  <%= f.number_field :actualCost, class: "form-control", placeholder: "Enter Actual Cost", required: true %>
  <span class="help-block"><i>* This field is required (leave blank if you are editing and don't want to change the password)</i><span>
</div>

<div class="form-group">
  <%= f.label :Description %>
  <%= f.text_field :description, class: "form-control", placeholder: "Enter 
  description", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

app/views/admin/companies/debit.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">List of All Debits</h3> 
        </div>
        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <table id="user_index" class="table table-hover table-bordered table-striped dataTables-example table-responsive" role="grid">
                  <thead>
                    <tr>
                      <th> Ref#</th>
                      <th> Name </th>
                      <th> Buy/Sell </th>
                      <th> Paid Amount</th>
                      <th> Debit</th>
                      <th> Status </th>
                      <th> Date </th>
                      <th class="col-xs-1"> 
                      Action</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @companies.each do |company| %>
                      <tr>
                        <td> <%= company.id %> </td>
                        <td> <%= company.name %> </td>
                        <td> <%= company.bye_or_sell %> </td>

                        <td> <%= company.paidAmount %> </td>                     
                        <td> <%= company.debitAmount %> </td>
                        <td> <%= company.status %> </td>
                        <td> <%= company.updated_at.strftime("%d-%m-%Y") %> </td>

                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-eye"></i>'), payment_edit_admin_company_url(company), class: 'btn btn-sm btn-primary' %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                 
                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

app/views/admin/companies/edit.html.erb
<%= form_for @company, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Edit Company</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/companies/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_companies_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/companies/index.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">List of Companies</h3> 
        </div>
        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-hover table-bordered table-striped dataTables-example table-responsive" role="grid">
                  <thead>
                    <tr>
                      <th> Ref#</th>
                      <th> Name </th>
                      <th> Visa/Ticket </th>
                      <th> Quantity </th>
                      <th> Buy/Sell</th>
                      <th> Sale Price</th>
                      <th> Paid Amount</th>
                      <th> Debit</th>
                      <th> Actual Cost</th>
                      <th> Margin </th>
                      
                      
                     
                     
                      <th class="col-xs-2">Actions</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @companies.each do |company| %>
                      <tr>
                        <td> <%= company.id %> </td>
                        <td> <%= company.name %> </td>
                        <td> <%= company.visa_or_ticket %> </td>
                        <td> <%= company.quantity %> </td>
                        <td> <%= company.bye_or_sell %> </td>
                        <td> <%= company.salePrice %> </td>
                        <td> <%= company.paidAmount %> </td>                     
                        <td> <%= company.debitAmount %> </td>
                        <td> <%= company.actualCost %> </td>
                        <td> <%= company.profit %> </td>
                        
                <!--        <td> <%= company.bye_or_sell.present? ? status_value(company.bye_or_sell) : company.bye_or_sell %> </td> -->                                             

                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-eye"></i>'), admin_company_url(company), class: 'btn btn-sm btn-primary' %>
                            <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_admin_company_url(company), class: 'btn btn-sm btn-warning' %>
                            
                          
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                 
                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

app/views/admin/companies/new.html.erb
<%= form_for @company, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">New Company</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/companies/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_companies_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/companies/payment_edit.html.erb
<%= form_for @company, url: debit_payment_admin_companies_path, method: :post, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Edit Payment</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/companies/debitPaymentform', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_companies_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/companies/show.html.erb
          
        
        <!--
          <button type="button" class="btn btn-success pull-right" style="margin-right: 27px;">
            <i class="fa fa-credit-card"></i> Submit Payment
          </button>
          <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
            <i class="fa fa-download"></i> Generate PDF
          </button>
        </div>
      </div>
      -->
<div class="row">
  <div class="col-xs-12">
    <div class="box">
              <div class="box-header">
                <h3 class="box-title"><%=@company.name%></h3>
                
              </div>
              <!-- /.box-header -->
              <div class="box-body no-padding">
                <table class="table table-striped">
                  <% for attribute in @company.attributes.keys do  %>
                    <tr>
                      <th style="width:200px;"> <%= attribute.humanize%></th>
                      <td> <%= @company.attributes[attribute].to_s %> </td>
                    </tr>
                  <% end %>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
          </div>
        </div>