config/routes.rb
Rails.application.routes.draw do
  
  
  get 'home/index'

  # Back admin routes start
  authenticate :user do
  namespace :admin do
    resources :visits do
      member do
        get 'print'
        get 'preview'
        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :tickets do
      member do
        get 'print'
        get 'preview'
        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :users do

    end
    resources :companies do
      member do

        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :deals do

    end
    resources :expenses do

    end

    # Admin root
    root to: 'application#index'
  end
  end
  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # Application root
 # root to: 'application#home'
  # Front routes end
 

  root to: 'creatives#index'
end

app/models/visit.rb
class Visit < ApplicationRecord
  before_create :calculate_margin
  before_update :calculate_margin
  before_create :calculate_debit
  before_update :calculate_debit
  before_create :set_client_status
  before_update :set_client_status
  before_update :client_debit_payment, if: :creditAmount?

  belongs_to :user


  def client_debit_payment
   if self.debitAmount.to_f > 0.0
   self.paidAmount = self.paidAmount.to_f + self.creditAmount.to_f
   self.debitAmount = self.debitAmount.to_f - self.creditAmount.to_f
  end
  if self.debitAmount.to_f == 0.0
    self.status = "Cleared"
    else
      self.status = "Not Cleared"
    end
    self.creditAmount = 0.0
end

  def calculate_margin
    self.profit = self.salePrice.to_f - self.actualCost.to_f
  end

  def calculate_debit
    self.debitAmount = self.salePrice.to_f - self.paidAmount.to_f
  end

  def set_client_status
  	if self.salePrice.to_f - self.paidAmount.to_f == 0.0
  		self.status = "Cleared"
  	else
  		self.status = "Not Cleared"
    end
 end
end

app/controllers/admin/visits_controller.rb
module Admin
  class VisitsController < Admin::ApplicationController
    respond_to :json, :html
    before_action :set_visit, only: [:show, :edit, :update, :destroy, :print, :preview, :payment_edit]
    layout  'admin/layouts/admin'
 
    # GET /users
    # GET /users.json
    def index
      if current_user.admin?
        @visits = Visit.all
      else
        @visits = current_user.visits
      end 
    end

    def payment_edit
    end


     # Post
    def debit_payment
      if current_user.admin?
      @visit = Visit.find(params[:visit][:id])
    else
      @visit = current_user.visits.find(params[:visit][:id])
    end 
      if @visit.update(visit_params)
        flash[:notice] = t('admin.visits.update.success')
        redirect_to admin_visits_url 
      else
        flash[:warning] = @visit.errors.full_messages.uniq.join(', ')
        respond_with :edit, :admin, :visit
      end
    end

    # GET /users/1
    # GET /users/1.json
    def debit
      @visits =[]
      if current_user.admin?
        visits = Visit.where(status: "Not Cleared").ids
      else
      visits = current_user.visits.where(status: "Not Cleared").ids
    end 
      visits.each do | visit|
        v = Visit.find(visit)
        @visits << v
      end
      @visits
    end
  
    def show
        respond_to do |format|
      format.html   
      format.json
      format.pdf { render template: 'admin/visits/report', pdf: 'report', layout: 'layouts/pdf'}
    end
    end

    def preview
        respond_to do |format|
      format.html   
    end   
    end

      def print
        respond_to do |format|
        format.html {render template: 'admin/visits/invoice' , layout: false} 
      end
  
    end

    # GET /users/new
    def new
      @visit = Visit.new
      @url = admin_visits_path
    end

    # GET /users/1/edit
    def edit
      @url = admin_visit_path(@visit)
    end

    # POST /users
    # POST /users.json
    def create
      @visit = current_user.visits.build(visit_params)

      if @visit.save
        flash[:notice] = t('admin.visits.create.success')
        redirect_to admin_visits_url 
      else
        flash[:warning] = @visit.errors.full_messages.uniq.join(', ')
        respond_with :new, :admin, :visit
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      if @visit.update(visit_params)
        flash[:notice] = t('admin.visits.update.success')
        redirect_to admin_visits_url 
      else
        flash[:warning] = @visit.errors.full_messages.uniq.join(', ')
        respond_with :edit, :admin, :visit
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @visit.destroy
      respond_to do |format|
        format.html { redirect_to admin_visits_path, notice: t('admin.visits.destroy.success') }
        format.json { head :no_content }
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    private def set_visit
       if current_user.admin?
        if Visit.exists?(params[:id])
        @visit = Visit.find(params[:id])
        else
        render :file => "#{Rails.root}/public/404",  layout: false, status: :not_found
        end 

      else
        
        if current_user.visits.exists?(params[:id])
        @visit = current_user.visits.find(params[:id])
        else
        render :file => "#{Rails.root}/public/404",  layout: false, status: :not_found
        end 
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    private def visit_params
      params.require(:visit).permit(Visit.attribute_names.map(&:to_sym))
    end
  end
end

app/helpers/admin/visits_helper.rb
module Admin::VisitsHelper

def country_name (record) 
	
    country = ISO3166::Country[record]
    cc = country.translations[I18n.locale.to_s] || country.name
    
  
  end
end

app/views/admin/visits/_form.html.erb
<div class="form-group">
  <%= f.label :Name %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter Name", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Phone %>
  <%= f.text_field :phone, class: "form-control", placeholder: "Enter Phone", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>


<div class="form-group">
  <%= f.label :Visa_Type , :class => "col-xs-12", style:"padding-left:0px;"%>
  <%= f.select :visaType, options_for_select(['Visit Visa','Umra Visa(Mofa only)','Umra Visa(Mofa + Accomodation)','Umra Visa(Mofa + Accomodation + Ticket)'],selected: @visit.visaType.present? ? @visit.visaType : ''), {:include_blank => true}, {:multiple => false, :class => "js-example-basic-single col-xs-12", :label => false,:style => "margin-left:25px;", :data => {:placeholder => ' select visa type details'}}%>  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Quantity %>
  <%= f.number_field :quantity, class: "form-control", placeholder: "Enter Quantity", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Adult  %>
  <%= f.number_field :adult, class: "form-control", placeholder: "Enter Quantity", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Child %>
  <%= f.number_field :child, class: "form-control", placeholder: "Enter Quantity", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Infant %>
  <%= f.number_field :infant, class: "form-control", placeholder: "Enter Quantity", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :country , :class => "col-xs-12", style:"padding-left:0px;" %>
  <%= f.country_select :countryCode  ,{:include_blank => true}, {:multiple => false, :class => "js-example-basic-single col-xs-12", :label => false,:style => "margin-left:25px;", :data => {:placeholder => 'choose country'}} %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Visa_Documents , :class => "col-xs-12", style:"padding-left:0px;" %>
  <%= f.select :visaWith, options_for_select(['Visa With Document','Visa Without Document','Not Described'],selected: @visit.visaWith.present? ? @visit.visaWith : ''), {:include_blank => true}, {:multiple => false, :class => "js-example-basic-single col-xs-12", :label => false,:style => "margin-left:25px;", :data => {:placeholder => ' select visa with document or without document'}}%>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Days , :class => "col-xs-12", style:"padding-left:0px;" %>
  <%= f.select :days, options_for_select(['15','21','28','Not Described'],selected: @visit.days.present? ? @visit.days : ''), {:include_blank => true}, {:multiple => false, :class => "js-example-basic-single col-xs-12", :label => false,:style => "margin-left:25px;", :data => {:placeholder => ' select number of days'}}%>  <span class="help-block"><i>* This field is required</i><span>
</div>


<div class="form-group">
  <%= f.label :Description %>
  <%= f.text_field :description, class: "form-control", placeholder: "Enter 
  description", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Sale_Price %>
  <%= f.number_field :salePrice, class: "form-control", placeholder: "Enter Amount", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Paid_Amount %>
  <%= f.number_field :paidAmount, class: "form-control", placeholder: "Enter Amount", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<!--
<div class="form-group">
  <%= f.label :debit %>
  <%= f.number_field :debitAmount, class: "form-control", placeholder: "Enter Debit", required: true %>
  <span class="help-block"><i>* This field is required (leave blank if you are editing and don't want to change the password)</i><span>
</div>
-->
<div class="form-group">
  <%= f.label :Actual_Cost %>
  <%= f.number_field :actualCost, class: "form-control", placeholder: "Enter Actual Cost", required: true %>
  <span class="help-block"><i>* This field is required (leave blank if you are editing and don't want to change the password)</i><span>
</div>
<!--
<div class="form-group">
  <%= f.label :Client_Payment_Status , :class => "col-xs-12", style:"padding-left:0px;" %>
  <%= f.select :status, options_for_select(['cleared','Not Cleared'],selected: @visit.status.present? ? @visit.status : ''), {:include_blank => true}, {:multiple => false, :class => "js-example-basic-single col-xs-12", :label => false,:style => "margin-left:25px;", :data => {:placeholder => ' select payment status'}}%>  <span class="help-block"><i>* This field is required</i><span>
</div>
-->
<%= f.hidden_field :profit, :value => '' %>
<%= f.hidden_field :debitAmount, :value => '' %>
<%= f.hidden_field :status, :value => '' %>




<!--
<div class="form-group">
  <%= f.label :credit %>
  <%= f.number_field :creditAmount, class: "form-control", placeholder: "Enter Credit", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
-->

app/views/admin/visits/debit.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">List of All Debits</h3> 
        </div>
        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-bordered table-striped dataTables-example table-responsive" role="grid">
                  <thead>
                    <tr>
                      <th> Ref#</th>
                      <th> Name </th>
                      <th> Phone</th>
                      <th> Paid Amount</th>
                      <th> Debit</th>
                      <th> Status </th>
                      <th> Date </th>
                      <th class="col-xs-1"> 
                      Action</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @visits.each do |visit| %>
                      <tr>
                        <td> <%= visit.id %> </td>
                        <td> <%= visit.name %> </td>
                       
                       <td> <%= visit.phone %> </td>
                        <td> <%= visit.paidAmount %> </td>                     
                        <td> <%= visit.debitAmount %> </td>
                        <td> <%= visit.status %> </td>
                        <td> <%= visit.updated_at.strftime("%d-%m-%Y") %> </td>

                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-eye"></i>'), payment_edit_admin_visit_url(visit), class: 'btn btn-sm btn-primary' %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                 
                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

app/views/admin/visits/edit.html.erb
<%= form_for @visit, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Edit Visit</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/visits/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_visits_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/visits/index.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">List of Visas</h3> 
        </div>
        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-hover table-bordered table-striped dataTables-example table-responsive" role="grid">
                  <thead>
                    <tr>
                      <th> Ref#</th>
                      <th> Name </th>
                      <th> Quantity </th>
                      <th>Sale Price</th>
                      <th>Paid Amount</th>
                      <th>Debit</th>
                      <th>Actual Cost</th>
                      <th> Margin </th>
                      <th> Status </th>
                      <th> Date </th>
                      <th class="col-xs-2">Actions</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @visits.each do |visit| %>
                      <tr>
                        <td> <%= visit.id %> </td>
                        <td> <%= visit.name %> </td>
                        <td> <%= visit.quantity %> </td>
                   <!--    <td> <%= visit.countryCode.present? ? country_name(visit.countryCode) : visit.countryCode %> </td> -->
                        <td> <%= visit.salePrice %> </td>
                        <td> <%= visit.paidAmount %> </td>                     
                        <td> <%= visit.debitAmount %> </td>
                        <td> <%= visit.actualCost %> </td>
                        <td> <%= visit.profit %> </td>
                        <td> <%= visit.status %> </td>

                        <td> <%= visit.updated_at.strftime("%d-%m-%Y") %> </td>

                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-eye"></i>'), admin_visit_url(visit), class: 'btn btn-sm btn-primary' %>
                            <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_admin_visit_url(visit), class: 'btn btn-sm btn-warning' %>
                            <%= link_to raw('<i class="fa fa-trash"></i>'), admin_visit_url(visit), class: 'btn btn-sm btn-danger',           method: :delete,
                                            data: { confirm: 'Are you sure you want to delete this ?' } %>

                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                 
                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

app/views/admin/visits/new.html.erb
<%= form_for @visit, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">New Visit</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/visits/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_visits_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/visits/show.html.erb
<div class="row no-print">
        <div class="col-xs-12">
          
        
        <!--
          <button type="button" class="btn btn-success pull-right" style="margin-right: 27px;">
            <i class="fa fa-credit-card"></i> Submit Payment
          </button>
          <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
            <i class="fa fa-download"></i> Generate PDF
          </button>
        </div>
      </div>
      -->
<div class="row">
  <div class="col-xs-12">
    <div class="box">
              <div class="box-header">
                <h3 class="box-title"><%=@visit.name%></h3>
                <%= link_to "view report", preview_admin_visit_path(@visit),class: "btn btn-large btn-info fa fa-report pull-right", style:"margin-left: 22px;" %>
              </div>
              <!-- /.box-header -->
              <div class="box-body no-padding">
                <table class="table table-striped">
                  <% for attribute in @visit.attributes.keys do  %>
                    <tr>
                      <th style="width:200px;"> <%= attribute.humanize%></th>
                      <td> <%= @visit.attributes[attribute].to_s %> </td>
                    </tr>
                  <% end %>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
          </div>
        </div>