config/routes.rb
Rails.application.routes.draw do
  
  
  get 'home/index'

  # Back admin routes start
  authenticate :user do
  namespace :admin do
    resources :visits do
      member do
        get 'print'
        get 'preview'
        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :tickets do
      member do
        get 'print'
        get 'preview'
        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :users do

    end
    resources :companies do
      member do

        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :deals do

    end
    resources :expenses do

    end

    # Admin root
    root to: 'application#index'
  end
  end
  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # Application root
 # root to: 'application#home'
  # Front routes end
 

  root to: 'creatives#index'
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  before_create :calculate_margin
  before_update :calculate_margin
  before_create :calculate_debit
  before_update :calculate_debit
  before_create :set_client_status
  before_update :set_client_status
  before_update :client_debit_payment, if: :creditAmount?

  belongs_to :user


  def client_debit_payment
   if self.debit.to_f > 0.0
   self.paidAmount = self.paidAmount.to_f + self.creditAmount.to_f
   self.debit = self.debit.to_f - self.creditAmount.to_f
  end
  if self.debit.to_f == 0.0
    self.status = "Cleared"
    else
      self.status = "Not Cleared"
    end
    self.creditAmount = 0.0
end

  def calculate_margin
    self.margin = self.sale_price.to_f - self.actual_price.to_f
  end

  def calculate_debit
    self.debit = self.sale_price.to_f - self.paidAmount.to_f
  end

  def set_client_status
  	if self.sale_price.to_f - self.paidAmount.to_f == 0.0
  		self.status = "Cleared"
  	else
  		self.status = "Not Cleared"
    end
 end
end

app/controllers/admin/tickets_controller.rb
module Admin
  class TicketsController < Admin::ApplicationController
    respond_to :json, :html
    before_action :set_ticket, only: [:show, :edit, :update, :destroy, :print, :preview, :payment_edit]
    layout  'admin/layouts/admin'
 
    # GET /users
    # GET /users.json
    def index
      if current_user.admin?
        @tickets = Ticket.all
      else
        @tickets = current_user.tickets
      end 
    end
    
    def payment_edit
    end


     # Post
    def debit_payment
      if current_user.admin?
      @ticket = Ticket.find(params[:ticket][:id])
    else
      @ticket = current_user.tickets.find(params[:ticket][:id])
    end 
      if @ticket.update(ticket_params)
        flash[:notice] = t('admin.tickets.update.success')
        redirect_to admin_tickets_url 
      else
        flash[:warning] = @ticket.errors.full_messages.uniq.join(', ')
        respond_with :edit, :admin, :ticket
      end
    end

    # GET /users/1
    # GET /users/1.json
    def debit
      @tickets =[]
      if current_user.admin?
        tickets = Ticket.where(status: "Not Cleared").ids
      else
      tickets = current_user.tickets.where(status: "Not Cleared").ids
    end 
      tickets.each do | ticket|
        v = Ticket.find(ticket)
        @tickets << v
      end
      @tickets
    end
  
    def show
        respond_to do |format|
      format.html   
      format.json
      format.pdf { render template: 'admin/tickets/report', pdf: 'report', layout: 'layouts/pdf'}
    end
    end

    def preview
        respond_to do |format|
      format.html   
    end   
    end

      def print
        respond_to do |format|
        format.html {render template: 'admin/tickets/invoice' , layout: false} 
      end
  
    end

    # GET /users/new
    def new
      @ticket = Ticket.new
      @url = admin_tickets_path
    end

    # GET /users/1/edit
    def edit
      @url = admin_ticket_path(@ticket)
    end

    # POST /users
    # POST /users.json
    def create
      @ticket = current_user.tickets.build(ticket_params)

      if @ticket.save
        flash[:notice] = t('admin.tickets.create.success')
        redirect_to admin_tickets_url 
      else
        flash[:warning] = @ticket.errors.full_messages.uniq.join(', ')
        respond_with :new, :admin, :ticket
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      if @ticket.update(ticket_params)
        flash[:notice] = t('admin.tickets.update.success')
        redirect_to admin_tickets_url 
      else
        flash[:warning] = @ticket.errors.full_messages.uniq.join(', ')
        respond_with :edit, :admin, :ticket
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @ticket.destroy
      respond_to do |format|
        format.html { redirect_to admin_tickets_path, notice: t('admin.tickets.destroy.success') }
        format.json { head :no_content }
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    private def set_ticket
      
      
      if current_user.admin?
        if Ticket.exists?(params[:id])
        @ticket = Ticket.find(params[:id])
        else
        render :file => "#{Rails.root}/public/404",  layout: false, status: :not_found
        end 

      else
        
        if current_user.tickets.exists?(params[:id])
        @ticket = current_user.tickets.find(params[:id])
        else
        render :file => "#{Rails.root}/public/404",  layout: false, status: :not_found
        end 
      end 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    private def ticket_params
      params.require(:ticket).permit(Ticket.attribute_names.map(&:to_sym))
  end
  end
end

app/views/admin/tickets/_debitPaymentform.html.erb
<div class="form-group">
  <%= f.label :Enter_Amount %>
  <%= f.number_field :creditAmount, class: "form-control", placeholder: "Enter Amount", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<%= f.hidden_field :paidAmount, :value => @ticket.paidAmount %>
<%= f.hidden_field :debit, :value => @ticket.debit %>
<%= f.hidden_field :status, :value => @ticket.status %>
<%= f.hidden_field :id, :value => @ticket.id %>

app/views/admin/tickets/_form.html.erb
<div class="form-group">
  <%= f.label :Name %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter Name", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Phone %>
  <%= f.text_field :phone, class: "form-control", placeholder: "Enter from", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Airline , :class => "col-xs-12", style:"padding-left:0px;"%>
  <%= f.select :airline, options_for_select(['Saudi Arabian Airlines','Swissair','African Airline International','Air Canada','Air China','Air France','Air Mauritius','Air Tanzania','Alitalia','Australian Airlines','Balgarian Airlines','Belgium World Airlines','Biman Bangladesh Airlines','Canadian Pacific Airlines','Egypt Air','Indian Airlines','Japan Airlines','Kuwait Airways','Pan-Amrican World Airways Inc.','Singapore Airlines','Sudan Airways','Syrian Arab Airlines','Turkish Airlines','Korean Air','Aeroflot Airline','Air Lanka Limited','Alia The Royal Jordanian Airline','American Airlines','Austrian Airlines','Balkan Bulgarian Airlines','British Airways','Canadian Airlines International','Cathay Pacific Airways Limited','Czech Airlines','Ethiopian Airlines','Eva Air The Wings Of Taiwan','Gulf Air','Iran Air','Iraqi Air','Kenya Airlines','Libyan Arab Airlines','Lot-Polish Airline','Malaysian Airlines','Melew Hangarian Airlines','Olympic Airways','Philippine Airlines','Royal Jordanian Airline','Royal Nepal Airlines Corporation','Scandinavian Airlines System, Sas','Thai Airways International','Trans World Airlines (Twa)','Turkmenistan Airlines','United Airlines','Yemen Airways','Yugoslav Airlines','Safe Air International','Shaheen Air International','Bhoja Airlines (Pvt) Limited','Klm Royal Dutch Airlines','Pakistan International Airline','Aero Asia'],selected: @ticket.airline.present? ? @ticket.airline : ''), {:include_blank => true}, {:multiple => false, :class => "js-example-basic-single col-xs-12", :label => false,:style => "margin-left:25px;", :data => {:placeholder => ' select visa type details'}}%>  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Sector %>
  <%= f.text_field :sector, class: "form-control", placeholder: "Enter sector", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Ticket_no %>
  <%= f.text_field :ticket_no, class: "form-control", placeholder: "Enter ticket no", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Airline_Pnr %>
  <%= f.text_field :airline_pnr, class: "form-control", placeholder: "Enter Airline Pnr", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Gds_Pnr %>
  <%= f.text_field :gds_pnr, class: "form-control", placeholder: "Enter Gds_Pnr", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Quantity %>
  <%= f.number_field :quantity, class: "form-control", placeholder: "Enter Quantity", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Adult  %>
  <%= f.number_field :adult, class: "form-control", placeholder: "Enter Quantity", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Child %>
  <%= f.number_field :child, class: "form-control", placeholder: "Enter Quantity", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Infant %>
  <%= f.number_field :infant, class: "form-control", placeholder: "Enter Quantity", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>



<div class="form-group">
  <%= f.label :Description %>
  <%= f.text_field :description, class: "form-control", placeholder: "Enter 
  description", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Sale_Price %>
  <%= f.number_field :sale_price, class: "form-control", placeholder: "Enter Amount", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>
<div class="form-group">
  <%= f.label :Paid_Amount %>
  <%= f.number_field :paidAmount, class: "form-control", placeholder: "Enter Amount", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :Actual_Cost %>
  <%= f.number_field :actual_price, class: "form-control", placeholder: "Enter Actual Cost", required: true %>
  <span class="help-block"><i>* This field is required (leave blank if you are editing and don't want to change the password)</i><span>
</div>

<%= f.hidden_field :margin, :value => '' %>
<%= f.hidden_field :debitAmount, :value => '' %>
<%= f.hidden_field :status, :value => '' %>

app/views/admin/tickets/debit.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">List of All Ticket Debits</h3> 
        </div>
        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
               <!--
                <table id="user_index " class="table table-bordered table-striped dataTable" role="grid"> 
                -->
              <table id="user_index" class="table table-bordered table-striped dataTables-example table-responsive" role="grid">                  <thead>
                    <tr>
                      <th> Ref#</th>
                      <th> Name </th>
                      <th> Phone</th>
                      <th> Paid Amount</th>
                      <th> Debit</th>
                      <th> Status </th>
                      <th> Date </th>
                      <th class="col-xs-1"> 
                      Action</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @tickets.each do |ticket| %>
                      <tr>
                        <td> <%= ticket.id %> </td>
                        <td> <%= ticket.name %> </td>
                       
                       <td> <%= ticket.phone %> </td>
                        <td> <%= ticket.paidAmount %> </td>                     
                        <td> <%= ticket.debit %> </td>
                        <td> <%= ticket.status %> </td>
                        <td> <%= ticket.updated_at.strftime("%d-%m-%Y") %> </td>

                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-eye"></i>'), payment_edit_admin_ticket_url(ticket), class: 'btn btn-sm btn-primary' %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                 
                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

app/views/admin/tickets/edit.html.erb
<%= form_for @ticket, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Edit Ticket</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/tickets/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_tickets_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/tickets/index.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">List of Tickets</h3> 
        </div>
        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-bordered table-striped dataTables-example table-responsive" role="grid">
                  <thead>
                    <tr>
                      <th> Ref#</th>
                      <th> Name </th>
                      <th> Quantity </th>
                      <th>Sale Price</th>
                      <th>Paid Amount</th>
                      <th>Debit</th>
                      <th>Actual Cost</th>
                      <th> Margin </th>
                      <th> Status </th>
                      <th> Date </th>
                      <th class="col-xs-2">Actions</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @tickets.each do |ticket| %>
                      <tr>
                        <td> <%= ticket.id %> </td>
                        <td> <%= ticket.name %> </td>
                        <td> <%= ticket.quantity %> </td>
                        <td> <%= ticket.sale_price %> </td>
                        <td> <%= ticket.paidAmount %> </td>                     
                        <td> <%= ticket.debit %> </td>
                        <td> <%= ticket.actual_price %> </td>
                        <td> <%= ticket.margin %> </td>
                        <td> <%= ticket.status %> </td>

                        <td> <%= ticket.updated_at.strftime("%d-%m-%Y") %> </td>

                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-eye"></i>'), admin_ticket_url(ticket), class: 'btn btn-sm btn-primary' %>
                            <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_admin_ticket_url(ticket), class: 'btn btn-sm btn-warning' %>
                            <%= link_to raw('<i class="fa fa-trash"></i>'), admin_ticket_url(ticket), class: 'btn btn-sm btn-danger',           method: :delete,
                                            data: { confirm: 'Are you sure you want to delete this ?' } %>
                          <%= link_to raw('<i class="fa fa-bank"></i>'), preview_admin_ticket_url(ticket), class: 'btn btn-sm btn-primary' %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                 
                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

app/views/admin/tickets/invoice.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title></title>

    <%= stylesheet_link_tag 'application_back', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body onload="window.print();">
  <div class="wrapper">

       <section class="invoice">
    <!-- title row -->
    <div class="row">
      <div class="col-xs-12">
        <h2 class="page-header">
          <%= image_tag('logo.png', :size => '700x120')%>
        </h2>
      </div>
        <!-- /.col -->
      </div>
      <div class="row">
      <div class="col-xs-9">
       <h4><b>Date: </b> <%= @ticket.updated_at.strftime("%d-%m-%Y")%></h4>
        
      </div>
      <div class="col-xs-3">
       <h4><b>Ref# </b> <%=@ticket.id%></h4>
        
      </div>
      <hr>
        <!-- /.col -->
      </div>
  <!--    <%= image_tag('logo.jpg', :size => '1100x120')%> -->
      <!-- info row -->
    <div class="row invoice-info">
      <div class="col-sm-7 invoice-col">
        From
        <address>
          <strong>The Fly Way Travel & Tours</strong><br>
          10-k Commercial Markeet Khawaja Bangloz<br>
          Abbasia Town, Rahim Yar Khan , Pakistan<br>
          Fax & Tel: (068)5952036<br>
          Email: theflywaytravels@gmail.com
        </address>
      </div>
      <!-- /.col -->
      <div class="col-sm-5 invoice-col">
        To
        <address>
          <strong><%= @ticket.name %></strong><br>
          Phone: <%= @ticket.phone %> <br>
         
        </address>
      </div>
      </div>
   
    <!-- /.row -->

    <!-- Table row -->
      <div class="row">
        <div class="col-xs-12">
          <table class="table table-striped">
                  <thead>
                    <tr>
                      <th>Airline </th>
                      <th>Sector</th>
                      <th>Quantity </th>
                    </tr>
                  </thead>

                  <tbody>
                      <tr>
                        
                        <td> <%= @ticket.airline %> </td>
                        <td> <%= @ticket.sector %> </td> 
                        <td> <%= @ticket.quantity %> : (<%= @ticket.adult %> Adult, <%= @ticket.child %> Child, <%= @ticket.infant %> Infant) </td>
                        

                        
                      </tr>
                  </tbody>

                 
                
          </table>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <div class="row">
        <!-- accepted payments column -->
        <div class="col-xs-6">
          <p class="lead">Description:</p>
          <p class="text-muted well well-sm no-shadow" style="margin-top: 5px;">
            <%= @ticket.description %>
          </p>
        </div>
        <!-- /.col -->
        <div class="col-xs-6">
          <p class="lead">Payment Details</p>

          <div class="table-responsive">
            <table class="table">
              <tr>
                <th style="width:50%">Total Amount:</th>
                <td><%= @ticket.sale_price%></td>
              </tr>
              <tr>
                <th>Paid Amount</th>
                <td><%= @ticket.paidAmount%></td>
              </tr>
              <tr>
                <th>Remaining Amount</th>
                <td><%= @ticket.debit%></td>
              </tr>
              <tr>
                <th>Status:</th>
                <td><%= @ticket.status%></td>
              </tr>
            </table>
          </div>
        </div>
        <!-- /.col -->
      </div>
      <div class="row">
      <div class="col-xs-6">
       <h4><b>Owner Signature :</h4>
        
      </div>
      <div class="col-xs-6">
       <h4><b>Client Signature: </h4>
        
      </div>
      <!-- /.row -->

      <!-- this row will not appear when printing -->
      
    </section>
  <!-- /.content -->
  
</div>
      
  </body>

  <%= javascript_include_tag 'application_back' %>

 
</html>

    
   

app/views/admin/tickets/new.html.erb
<%= form_for @ticket, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">New Ticket</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/tickets/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_tickets_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/tickets/payment_edit.html.erb
<%= form_for @ticket, url: debit_payment_admin_tickets_path, method: :post, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Edit Payment</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/tickets/debitPaymentform', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_tickets_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/tickets/preview.html.erb
    <!-- Content Header (Page header) -->
  

    <div class="row no-print">
        <div class="col-xs-12">
          
        <%= link_to " Print", print_admin_ticket_path(@ticket), target: "_blank", class: "btn btn-large btn-default fa fa-print", style:"margin-left: 22px;" %>
        <!--
          <button type="button" class="btn btn-success pull-right" style="margin-right: 27px;">
            <i class="fa fa-credit-card"></i> Submit Payment
          </button>
          <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
            <i class="fa fa-download"></i> Generate PDF
          </button>
        </div>
      </div>
      -->

    <!-- Main content -->
     <section class="invoice">
    <!-- title row -->
    <div class="row">
      <div class="col-xs-12">
        <h2 class="page-header">
          <%= image_tag('logo.png', :size => '700x120')%>
        </h2>
      </div>
        <!-- /.col -->
      </div>
      <div class="row">
      <div class="col-xs-9">
       <h4><b>Date: </b> <%= @ticket.updated_at.strftime("%d-%m-%Y")%></h4>
        
      </div>
      <div class="col-xs-3">
       <h4><b>Ref# </b> <%=@ticket.id%></h4>
        
      </div>
      <hr>
        <!-- /.col -->
      </div>
  <!--    <%= image_tag('logo.jpg', :size => '1100x120')%> -->
      <!-- info row -->
    <div class="row invoice-info">
      <div class="col-sm-7 invoice-col">
        From
        <address>
          <strong>The Fly Way Travel & Tours</strong><br>
          10-k Commercial Markeet Khawaja Bangloz<br>
          Abbasia Town, Rahim Yar Khan , Pakistan<br>
          Fax & Tel: (068)5952036<br>
          Email: theflywaytravels@gmail.com
        </address>
      </div>
      <!-- /.col -->
      <div class="col-sm-5 invoice-col">
        To
        <address>
          <strong><%= @ticket.name %></strong><br>
          Phone: <%= @ticket.phone %> <br>
         
        </address>
      </div>
      </div>
   
    <!-- /.row -->

    <!-- Table row -->
      <div class="row">
        <div class="col-xs-12">
          <table class="table table-striped">
                  <thead>
                    <tr>
                      <th>Airline </th>
                      <th>Sector</th>
                      <th>Quantity </th>
                    </tr>
                  </thead>

                  <tbody>
                      <tr>
                        
                        <td> <%= @ticket.airline %> </td>
                        <td> <%= @ticket.sector %> </td> 
                        <td> <%= @ticket.quantity %> : (<%= @ticket.adult %> Adult, <%= @ticket.child %> Child, <%= @ticket.infant %> Infant) </td>
                        

                        
                      </tr>
                  </tbody>

                 
                
          </table>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <div class="row">
        <!-- accepted payments column -->
        <div class="col-xs-6">
          <p class="lead">Description:</p>
          <p class="text-muted well well-sm no-shadow" style="margin-top: 5px;">
            <%= @ticket.description %>
          </p>
        </div>
        <!-- /.col -->
        <div class="col-xs-6">
          <p class="lead">Payment Details</p>

          <div class="table-responsive">
            <table class="table">
              <tr>
                <th style="width:50%">Total Amount:</th>
                <td><%= @ticket.sale_price%></td>
              </tr>
              <tr>
                <th>Paid Amount</th>
                <td><%= @ticket.paidAmount%></td>
              </tr>
              <tr>
                <th>Remaining Amount</th>
                <td><%= @ticket.debit%></td>
              </tr>
              <tr>
                <th>Status:</th>
                <td><%= @ticket.status%></td>
              </tr>
            </table>
          </div>
        </div>
        <!-- /.col -->
      </div>
      <div class="row">
      <div class="col-xs-6">
       <h4><b>Owner Signature :</h4>
        
      </div>
      <div class="col-xs-6">
       <h4><b>Client Signature: </h4>
        
      </div>
      <!-- /.row -->

      <!-- this row will not appear when printing -->
      
    </section>
    </div>
    </div>
    <!-- /.content -->
   
  <!-- /.content-wrapper -->
    

app/views/admin/tickets/show.html.erb
<div class="row no-print">
        <div class="col-xs-12">
          
        
        <!--
          <button type="button" class="btn btn-success pull-right" style="margin-right: 27px;">
            <i class="fa fa-credit-card"></i> Submit Payment
          </button>
          <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
            <i class="fa fa-download"></i> Generate PDF
          </button>
        </div>
      </div>
      -->
<div class="row">
  <div class="col-xs-12">
    <div class="box">
              <div class="box-header">
                <h3 class="box-title"><%=@ticket.name%></h3>
                <%= link_to "view report", preview_admin_ticket_path(@ticket),class: "btn btn-large btn-info fa fa-report pull-right", style:"margin-left: 22px;" %>
              </div>
              <!-- /.box-header -->
              <div class="box-body no-padding">
                <table class="table table-striped">
                  <% for attribute in @ticket.attributes.keys do  %>
                    <tr>
                      <th style="width:200px;"> <%= attribute.humanize%></th>
                      <td> <%= @ticket.attributes[attribute].to_s %> </td>
                    </tr>
                  <% end %>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
          </div>
        </div>