config/routes.rb
Rails.application.routes.draw do
  
  
  get 'home/index'

  # Back admin routes start
  authenticate :user do
  namespace :admin do
    resources :visits do
      member do
        get 'print'
        get 'preview'
        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :tickets do
      member do
        get 'print'
        get 'preview'
        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :users do

    end
    resources :companies do
      member do

        get 'payment_edit'


      end
      collection do
        get :debit
        post :debit_payment
      end
    end
    resources :deals do

    end
    resources :expenses do

    end

    # Admin root
    root to: 'application#index'
  end
  end
  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # Application root
 # root to: 'application#home'
  # Front routes end
 

  root to: 'creatives#index'
end

app/views/admin/shared/_content_header.html.erb
<section class="content-header">
  <h1> <%= params[:controller].split('/').last.humanize %> </h1>
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-dashboard"></i> Home'.html_safe, admin_root_path %></li>
    <li class="active"> <%= params[:controller].split('/').last.humanize %> </li>
  </ol>
</section>
 <!-- Main content -->
    

app/views/admin/shared/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 1.0.0
  </div>
   <strong>The Fly Way Travel & Tours </strong>, <small>10-k Commercial Markeet Khawaja Bangloz Abbasia Town, Rahim Yar Khan</small>
</footer>

app/views/admin/shared/_header.html.erb
<header class="main-header">
  <%= content_tag :a, href: admin_root_path, class: 'logo' do %>
    <span class="logo-mini">
    <b>F</b>WT</span>
    <span class="logo-lg">
    <b>Flyway</b>Travel</span>
  <% end %>

  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag "http://placehold.it/160x160", class: "user-image" %>
            <span class="hidden-xs"><%= current_user.name %></span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <%= image_tag "http://placehold.it/160x160", class: "img-circle" %>

              <p>
                <%= current_user.name %>
                <small>Member since <%= current_user.created_at.strftime("%B, %Y") %></small>
              </p>
            </li>

            <li class="user-footer">
              <div class="pull-left">
                <%= link_to 'Profile', edit_admin_user_path(current_user), class: 'btn btn-default -btn-flat' %>
              </div>
              <div class="pull-right">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat' %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/admin/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h4>
        <i class="icon fa fa-<%= name.to_s == 'notice' ? 'check' : 'ban' %>"></i> 
        <%= name.to_s == 'notice' ? 'Success!' : 'Alert!' %>
      </h4>
      <%= content_tag :div, raw(msg.split(",").join("<br>").html_safe), :id => "flash_#{name}" %>
    </div>
    <% flash[name] = nil %>
  <% end %>
<% end %>

app/views/admin/shared/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">

    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "http://placehold.it/160x160", class: "img-circle" %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.name %></p>
        <%= link_to '<i class="fa fa-circle text-success"></i><span>Online</span>'.html_safe, admin_root_path %>
      </div>
    </div>
    <ul class="sidebar-menu">
      <li> <%= link_to '<i class="fa fa-dashboard"></i><span>Dashboard</span>'.html_safe, admin_root_path %> </li>
      <%  if current_user.admin? %>

      <li class="treeview">
        <a href="#">
          <i class="fa fa-users"></i>
          <span>Users</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-list"></i> List Users'.html_safe, admin_users_path %> </li>
          <li> <%= link_to '<i class="fa fa-user-plus"></i> Create User'.html_safe, new_admin_user_path %> </li>
        </ul>
      </li>
      <% end %>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-paper-plane"></i>
          <span>Visa</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-list"></i> List Visa'.html_safe, admin_visits_path %> </li>
          <li> <%= link_to '<i class="fa fa-user-plus"></i> Create  Visa'.html_safe, new_admin_visit_path %> </li>
          <li> <%= link_to '<i class="fa fa-bank"></i> All Debits'.html_safe, debit_admin_visits_path %> </li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-plane"></i>
          <span>Ticket</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-list"></i> List Ticket'.html_safe, admin_tickets_path %> </li>
          <li> <%= link_to '<i class="fa fa-user-plus"></i> Create Ticket'.html_safe, new_admin_ticket_path %> </li>
          <li> <%= link_to '<i class="fa fa-bank"></i> All Ticket Debits'.html_safe, debit_admin_tickets_path %> </li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-building-o"></i>
          <span>Companies</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-archive"></i> Create Company'.html_safe, new_admin_deal_path %> </li>
          <li> <%= link_to '<i class="fa fa-archive"></i> List Companies'.html_safe, admin_deals_path %> </li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-shopping-cart"></i>
          <span>Dealing Companies</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-list"></i> List Deals'.html_safe, admin_companies_path %> </li>
          <li> <%= link_to '<i class="fa fa-user-plus"></i> Create 
          Deal'.html_safe, new_admin_company_path %> </li> 
          <li> <%= link_to '<i class="fa fa-bank"></i> All Debits'.html_safe, debit_admin_companies_path %> </li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-money"></i>
          <span>Expenses</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-list"></i> List Expenses'.html_safe, admin_expenses_path %> </li>
          <li> <%= link_to '<i class="fa fa-user-plus"></i> Create 
          Expense'.html_safe, new_admin_expense_path %> </li> 
        </ul>
      </li>
      

    </ul>

  </section>
</aside>